#!/bin/bash
#Faxel
clear
toilet -f pagga         FACEBOOK          | lolcat
echo "Mise a jour de Facebook en cours........." | lolcat
echo ""
git pull origin master
echo "Mise à jour de Facebook terminer........." | lolcat
echo ""
figlet -f small Facebook a jour!   | lolcat
echo ""
toilet -f mono12 -F border Faxel   | lolcat
sleep 3
echo ""
clear
